version: "3.2"

services:
  tomcat:
    image: zhukovsd/typing-test-dev:latest
    environment:
      # this env tells Spring app to look for Redis host at "redis:6379" address
      - env=prod
    ports:
      - 80:8080

  redis:
    image: zhukovsd/typing-test-redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  redis-data: