version: "3.1"

services:
  tomcat:
    image: zhukovsd/typing-test:${TYPING_TEST_IMAGE_TAG}
    environment:
      - env=prod
    ports:
      - 80:8080

  redis:
    image: zhukovsd/typing-test-redis:latest
    volumes:
      - redis-data:/data

volumes:
  redis-data: