defaults: &defaults
  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: zhukovsd/typing-test-build-env:latest

    # working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - run:
          name: Build typing-test war
          command: |
            mv /frontend/node_modules ./frontend
            mvn package --offline

      - persist_to_workspace:
          root: .
          # Must be relative path from root
          paths:
            - Dockerfile
            - stack.yml
            - production-certs/*
            - target/*
            - ROOT.xml

  deploy-production:
    <<: *defaults
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: .

      - setup_remote_docker

      - run:
          name: Build and push typing-test Docker image
          command: |
            docker image build -t zhukovsd/typing-test:latest .
            docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
            docker image push zhukovsd/typing-test:latest

      - run:
          name: Deploy to production Swarm
          command: |
            openssl aes-256-cbc -d -in production-certs/ca.pem.enc -k $ENCRYPTION_KEY -out ca.pem
            openssl aes-256-cbc -d -in production-certs/cert.pem.enc -k $ENCRYPTION_KEY -out cert.pem
            openssl aes-256-cbc -d -in production-certs/key.pem.enc -k $ENCRYPTION_KEY -out key.pem

            docker --tlsverify --tlscacert=ca.pem --tlscert=cert.pem --tlskey=key.pem -H 88.99.12.213:2376 stack deploy -c stack.yml --with-registry-auth typing-test

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-production:
          requires:
            - build